import type { LevelConfig } from './LevelTypes';

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    id: 1,
    nameAr: 'أول يوم على الشاطئ',
    durationSeconds: 150,
    targetScore: 300,
    customerPatienceMultiplier: 1.4,
    queueSize: 3,
    allowedContainers: ['cup-small', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry'],
    allowedSauces: [],
    allowedToppings: [],
    minScoops: 1,
    maxScoops: 1,
    requireScoopOrder: false,
    extraIngredientsAllowed: true,
    customerSpawnDelaySeconds: 7,
    basePatienceSeconds: 55,
    sauceChance: 0,
    maxToppingsPerOrder: 0,
    customerKinds: ['regular'],
    goals: [{ type: 'score', value: 300, labelAr: 'اجمع 300 نقطة' }],
    allowRetryOnMistake: true,
    unlocksAr: ['كوب صغير', 'مخروط', 'فانيلا', 'شوكولاتة', 'فراولة'],
  },
  {
    id: 2,
    nameAr: 'رشّات ملونة',
    durationSeconds: 150,
    targetScore: 500,
    customerPatienceMultiplier: 1.25,
    queueSize: 4,
    allowedContainers: ['cup-small', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry'],
    allowedSauces: [],
    allowedToppings: ['sprinkles'],
    minScoops: 1,
    maxScoops: 2,
    requireScoopOrder: false,
    extraIngredientsAllowed: true,
    customerSpawnDelaySeconds: 6,
    basePatienceSeconds: 50,
    sauceChance: 0,
    maxToppingsPerOrder: 1,
    customerKinds: ['regular', 'kid'],
    goals: [
      { type: 'score', value: 500, labelAr: 'اجمع 500 نقطة' },
      { type: 'serve-customers', value: 6, labelAr: 'اخدم 6 زبائن' },
    ],
    allowRetryOnMistake: true,
    unlocksAr: ['رشات ملونة', 'سكوبان', 'زبون طفل'],
  },
  {
    id: 3,
    nameAr: 'نكهات استوائية',
    durationSeconds: 160,
    targetScore: 750,
    customerPatienceMultiplier: 1.15,
    queueSize: 4,
    allowedContainers: ['cup-small', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio'],
    allowedSauces: ['chocolate'],
    allowedToppings: ['sprinkles'],
    minScoops: 1,
    maxScoops: 2,
    requireScoopOrder: false,
    extraIngredientsAllowed: true,
    customerSpawnDelaySeconds: 6,
    basePatienceSeconds: 48,
    sauceChance: 0.45,
    maxToppingsPerOrder: 1,
    customerKinds: ['regular', 'kid', 'hurried'],
    goals: [
      { type: 'score', value: 750, labelAr: 'اجمع 750 نقطة' },
      { type: 'max-mistakes', value: 3, labelAr: 'لا تتجاوز 3 أخطاء' },
    ],
    allowRetryOnMistake: true,
    unlocksAr: ['مانجو', 'فستق', 'صوص شوكولاتة', 'زبون مستعجل'],
  },
  {
    id: 4,
    nameAr: 'كوب أكبر',
    durationSeconds: 165,
    targetScore: 1000,
    customerPatienceMultiplier: 1.1,
    queueSize: 5,
    allowedContainers: ['cup-small', 'cup-medium', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio'],
    allowedSauces: ['chocolate'],
    allowedToppings: ['sprinkles', 'nuts', 'cherry'],
    minScoops: 1,
    maxScoops: 3,
    requireScoopOrder: false,
    extraIngredientsAllowed: true,
    customerSpawnDelaySeconds: 5.5,
    basePatienceSeconds: 46,
    sauceChance: 0.5,
    maxToppingsPerOrder: 2,
    customerKinds: ['regular', 'kid', 'hurried'],
    goals: [
      { type: 'score', value: 1000, labelAr: 'اجمع 1000 نقطة' },
      { type: 'serve-customers', value: 10, labelAr: 'اخدم 10 زبائن' },
    ],
    allowRetryOnMistake: true,
    unlocksAr: ['كوب متوسط', 'مكسرات', 'كرز', '3 سكوبات'],
  },
  {
    id: 5,
    nameAr: 'الترتيب مهم',
    durationSeconds: 165,
    targetScore: 1300,
    customerPatienceMultiplier: 1,
    queueSize: 5,
    allowedContainers: ['cup-small', 'cup-medium', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio'],
    allowedSauces: ['chocolate', 'caramel'],
    allowedToppings: ['sprinkles', 'nuts', 'cherry'],
    minScoops: 2,
    maxScoops: 3,
    requireScoopOrder: true,
    extraIngredientsAllowed: false,
    customerSpawnDelaySeconds: 4.5,
    basePatienceSeconds: 44,
    sauceChance: 0.55,
    maxToppingsPerOrder: 2,
    customerKinds: ['regular', 'kid', 'hurried'],
    goals: [
      { type: 'score', value: 1300, labelAr: 'اجمع 1300 نقطة' },
      { type: 'combo-streak', value: 5, labelAr: 'نفّذ 5 طلبات صحيحة متتالية' },
    ],
    allowRetryOnMistake: false,
    unlocksAr: ['صوص كراميل', 'ترتيب السكوبات مهم'],
  },
  {
    id: 6,
    nameAr: 'توت وكريمة',
    durationSeconds: 170,
    targetScore: 1600,
    customerPatienceMultiplier: 0.9,
    queueSize: 6,
    allowedContainers: ['cup-small', 'cup-medium', 'cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio', 'berry', 'caramel'],
    allowedSauces: ['chocolate', 'caramel'],
    allowedToppings: ['sprinkles', 'nuts', 'cherry', 'oreo', 'whipped-cream'],
    minScoops: 2,
    maxScoops: 3,
    requireScoopOrder: true,
    extraIngredientsAllowed: false,
    customerSpawnDelaySeconds: 4,
    basePatienceSeconds: 40,
    sauceChance: 0.6,
    maxToppingsPerOrder: 2,
    customerKinds: ['regular', 'kid', 'hurried'],
    goals: [
      { type: 'score', value: 1600, labelAr: 'اجمع 1600 نقطة' },
      { type: 'no-lost-customers', value: 2, labelAr: 'لا تفقد أكثر من زبونين' },
    ],
    allowRetryOnMistake: false,
    unlocksAr: ['توت', 'كراميل', 'أوريو', 'كريمة'],
  },
  {
    id: 7,
    nameAr: 'زبائن مهمون',
    durationSeconds: 175,
    targetScore: 2000,
    customerPatienceMultiplier: 0.85,
    queueSize: 6,
    allowedContainers: ['cup-small', 'cup-medium', 'cup-large', 'cone', 'waffle-cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio', 'berry', 'caramel', 'mint'],
    allowedSauces: ['chocolate', 'caramel', 'strawberry'],
    allowedToppings: ['sprinkles', 'nuts', 'cherry', 'oreo', 'whipped-cream', 'chocolate-chips'],
    minScoops: 2,
    maxScoops: 3,
    requireScoopOrder: true,
    extraIngredientsAllowed: false,
    customerSpawnDelaySeconds: 3.5,
    basePatienceSeconds: 38,
    sauceChance: 0.65,
    maxToppingsPerOrder: 2,
    customerKinds: ['regular', 'kid', 'hurried', 'vip'],
    goals: [
      { type: 'score', value: 2000, labelAr: 'اجمع 2000 نقطة' },
      { type: 'serve-vip', value: 1, labelAr: 'اخدم زبون VIP بنجاح' },
    ],
    allowRetryOnMistake: false,
    unlocksAr: ['كوب كبير', 'وافل كون', 'نعناع', 'صوص فراولة', 'قطع شوكولاتة', 'زبون VIP'],
  },
  {
    id: 8,
    nameAr: 'ذروة الصيف',
    durationSeconds: 180,
    targetScore: 2600,
    customerPatienceMultiplier: 0.75,
    queueSize: 7,
    allowedContainers: ['cup-small', 'cup-medium', 'cup-large', 'cone', 'waffle-cone'],
    allowedFlavors: ['vanilla', 'chocolate', 'strawberry', 'mango', 'pistachio', 'berry', 'caramel', 'mint'],
    allowedSauces: ['chocolate', 'caramel', 'strawberry'],
    allowedToppings: ['sprinkles', 'nuts', 'cherry', 'oreo', 'whipped-cream', 'chocolate-chips', 'fruit'],
    minScoops: 2,
    maxScoops: 3,
    requireScoopOrder: true,
    extraIngredientsAllowed: false,
    customerSpawnDelaySeconds: 3,
    basePatienceSeconds: 34,
    sauceChance: 0.7,
    maxToppingsPerOrder: 3,
    customerKinds: ['regular', 'kid', 'hurried', 'vip'],
    goals: [
      { type: 'score', value: 2600, labelAr: 'اجمع 2600 نقطة' },
      { type: 'earn-coins', value: 350, labelAr: 'اجمع 350 عملة' },
      { type: 'max-mistakes', value: 2, labelAr: 'لا تتجاوز خطأين' },
    ],
    allowRetryOnMistake: false,
    unlocksAr: ['قطع فواكه', 'جميع المكونات'],
  },
];

export function getLevelConfig(id: number): LevelConfig | undefined {
  return LEVEL_CONFIGS.find((l) => l.id === id);
}
